apiVersion: apps/v1
kind: Deployment
metadata:
  name: reproa-frontend
  namespace: reproa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reproa-frontend
  template:
    metadata:
      labels:
        app: reproa-frontend
    spec:
      containers:
      - name: frontend
        image: reprostat/reproa-k8s_frontend:dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 80
