apiVersion: v1
kind: Service
metadata:
  name: reproa-access
  namespace: reproa
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: reproa-frontend